export const costs = {
  // Major metro connections
  'Mumbai-Delhi':       { flight: 5000, train: 3000 },
  'Delhi-Mumbai':       { flight: 5000, train: 3000 },
  'Mumbai-Bangalore':   { flight: 6000, train: 2500 },
  'Bangalore-Mumbai':   { flight: 6000, train: 2500 },
  'Mumbai-Hyderabad':   { flight: 4500, train: 2800 },
  'Hyderabad-Mumbai':   { flight: 4500, train: 2800 },
  'Mumbai-Chennai':     { flight: 5500, train: 3000 },
  'Chennai-Mumbai':     { flight: 5500, train: 3000 },
  'Mumbai-Kolkata':     { flight: 7000, train: 4000 },
  'Kolkata-Mumbai':     { flight: 7000, train: 4000 },
  'Mumbai-Goa':         { flight: 3500, train: 1800 },
  'Goa-Mumbai':         { flight: 3500, train: 1800 },
  'Mumbai-Pune':        { flight: 2000, train: 500  },
  'Pune-Mumbai':        { flight: 2000, train: 500  },
  'Mumbai-Ahmedabad':   { flight: 4000, train: 2000 },
  'Ahmedabad-Mumbai':   { flight: 4000, train: 2000 },
  'Delhi-Chennai':      { flight: 4500, train: 3200 },
  'Chennai-Delhi':      { flight: 4500, train: 3200 },
  'Delhi-Kolkata':      { flight: 4000, train: 2800 },
  'Kolkata-Delhi':      { flight: 4000, train: 2800 },
  'Delhi-Bangalore':    { flight: 5500, train: 3500 },
  'Bangalore-Delhi':    { flight: 5500, train: 3500 },
  'Delhi-Hyderabad':    { flight: 5500, train: 3500 },
  'Hyderabad-Delhi':    { flight: 5500, train: 3500 },
  'Delhi-Jaipur':       { flight: 3000, train: 1500 },
  'Jaipur-Delhi':       { flight: 3000, train: 1500 },
  'Delhi-Agra':         { flight: 2500, train: 1000 },
  'Agra-Delhi':         { flight: 2500, train: 1000 },
  'Delhi-Amritsar':     { flight: 3800, train: 2200 },
  'Amritsar-Delhi':     { flight: 3800, train: 2200 },
  'Delhi-Lucknow':      { flight: 3200, train: 1800 },
  'Lucknow-Delhi':      { flight: 3200, train: 1800 },
  'Delhi-Patna':        { flight: 3800, train: 2200 },
  'Patna-Delhi':        { flight: 3800, train: 2200 },
  'Delhi-Bhopal':       { flight: 3500, train: 2000 },
  'Bhopal-Delhi':       { flight: 3500, train: 2000 },
  'Delhi-Indore':       { flight: 4000, train: 2200 },
  'Indore-Delhi':       { flight: 4000, train: 2200 },
  'Hyderabad-Bangalore':{ flight: 3500, train: 2000 },
  'Bangalore-Hyderabad':{ flight: 3500, train: 2000 },
  'Hyderabad-Chennai':  { flight: 3000, train: 1800 },
  'Chennai-Hyderabad':  { flight: 3000, train: 1800 },
  'Kolkata-Chennai':    { flight: 4200, train: 3000 },
  'Chennai-Kolkata':    { flight: 4200, train: 3000 },
  'Jaipur-Ahmedabad':   { flight: 3500, train: 2200 },
  'Ahmedabad-Jaipur':   { flight: 3500, train: 2200 },
  'Agra-Jaipur':        { flight: 2800, train: 1200 },
  'Jaipur-Agra':        { flight: 2800, train: 1200 },
  'Pune-Hyderabad':     { flight: 4000, train: 2500 },
  'Hyderabad-Pune':     { flight: 4000, train: 2500 },
  'Goa-Bangalore':      { flight: 3800, train: 2200 },
  'Bangalore-Goa':      { flight: 3800, train: 2200 },
  default:              { flight: 6500, train: 3800 },
}

export const nearbyPlaces = {
  Mumbai:    ['Gateway of India', 'Marine Drive', 'Elephanta Caves'],
  Delhi:     ['Red Fort', 'India Gate', 'Qutub Minar'],
  Bangalore: ['Bangalore Palace', 'UB City Mall', 'Lalbagh Botanical Garden'],
  Chennai:   ['Marina Beach', 'Kapaleeshwarar Temple', 'Fort St. George'],
  Kolkata:   ['Victoria Memorial', 'Howrah Bridge', 'Park Street'],
  Jaipur:    ['Amber Fort', 'Hawa Mahal', 'City Palace'],
  Agra:      ['Taj Mahal', 'Agra Fort', 'Fatehpur Sikri'],
  Goa:       ['Baga Beach', 'Fort Aguada', 'Dudhsagar Waterfalls'],
  Amritsar:  ['Golden Temple', 'Jallianwala Bagh', 'Wagah Border'],
  Pune:      ['Shaniwar Wada', 'Sinhagad Fort', 'Lonavla Hills'],
  Ahmedabad: ['Sabarmati Ashram', 'Sidi Saiyyed Mosque', 'Akshardham Temple'],
  Hyderabad: ['Charminar', 'Golconda Fort', 'Hussain Sagar Lake'],
  Surat:     ['Dutch Cemetery', 'Surat Castle', 'Ukai Dam'],
  Kanpur:    ['Kanpur Zoological Park', 'Massacre Ghat', 'Kahn Riverfront'],
  Lucknow:   ['Bara Imambara', 'Lucknow Museum', 'Rumi Darwaza'],
  Nagpur:    ['Ramtek Temple', 'Ambazari Lake', 'Sitabuldi Fort'],
  Patna:     ['Patna Museum', 'Golghar', 'Takht Sri Harmandir Sahib'],
  Indore:    ['Sarafa Bazaar', 'Raja Ramana Palace', 'Jhansi Ki Rani Statue'],
  Vadodara:  ['Lakshmi Vilas Palace', 'Sayaji Garden', 'Meer Khan Palace'],
  Bhopal:    ['Bhimbetka Caves', 'Upper Lake', 'Tribal Museum'],
  Ludhiana:  ['Pau Papne Wali Baoli', 'Jawahar Lal Nehru Planetarium', 'Atal Bihari Vajpayee Memorial'],
  Udaipur:   ['City Palace', 'Lake Pichola', 'Jag Mandir'],
  Shimla:    ['The Ridge', 'Mall Road', 'Jakhoo Temple'],
  Darjeeling:['Tiger Hill', 'Batasia Loop', 'Padmaja Naidu Himalayan Zoological Park'],
  Kochi:     ['Fort Kochi', 'Chinese Fishing Nets', 'Mattancherry Palace'],
  Mysore:    ['Mysore Palace', 'Chamundeshwari Temple', 'Brindavan Gardens'],
  Chandigarh: ["Rock Garden","Sukhna Lake","Rose Garden"],
  Guwahati: ["Kamakhya Temple","Umananda Island","Assam State Museum"],
  Bhubaneswar: ["Lingaraja Temple","Udayagiri Caves","Nandankanan Zoo"],
  Trivandrum: ["Padmanabhaswamy Temple","Napier Museum","Kovalam Beach"],
  Madurai: ["Meenakshi Temple","Thirumalai Nayakkar Mahal","Gandhi Museum"],
  Jodhpur: ["Mehrangarh Fort","Umaid Bhawan Palace","Jaswant Thada"],
  Pondicherry: ["Promenade Beach","Auroville","Paradise Beach"],
  Leh: ["Pangong Lake","Nubra Valley","Shanti Stupa"],
  Manali: ["Rohtang Pass","Solang Valley","Hidimba Temple"],
  Rishikesh: ["Laxman Jhula","Triveni Ghat","Parmarth Niketan"],
}

export const activities = {
  Mumbai:    ['Explore colonial architecture at Gateway of India', 'Stroll along Marine Drive', 'Take a ferry to Elephanta Caves'],
  Delhi:     ['Visit the Red Fort', 'Relax at India Gate', 'Climb Qutub Minar'],
  Bangalore: ['Tour Bangalore Palace', 'Shop at UB City', 'Walk in Lalbagh Garden'],
  Chennai:   ['Relax at Marina Beach', 'Pray at Kapaleeshwarar Temple', 'Explore Fort St. George'],
  Kolkata:   ['Visit Victoria Memorial', 'Cross Howrah Bridge', 'Enjoy food on Park Street'],
  Jaipur:    ['Visit Amber Fort', 'Photograph Hawa Mahal', 'Stroll through City Palace'],
  Agra:      ['Marvel at Taj Mahal', 'Tour Agra Fort', 'Day trip to Fatehpur Sikri'],
  Goa:       ['Sunbathe at Baga Beach', 'Explore Fort Aguada', 'Hike to Dudhsagar Waterfalls'],
  Amritsar:  ['Visit Golden Temple', 'See Jallianwala Bagh', 'Wagah Border ceremony'],
  Pune:      ['Explore Shaniwar Wada', 'Visit Sinhagad Fort', 'Relax in Lonavla hills'],
  Ahmedabad: ['Visit Sabarmati Ashram', 'See Sidi Saiyyed Mosque', 'Tour Akshardham Temple'],
  Hyderabad: ['See Charminar', 'Explore Golconda Fort', 'Boat on Hussain Sagar'],
  Surat:     ['Visit Dutch Cemetery', 'Tour Surat Castle', 'Drive to Ukai Dam'],
  Kanpur:    ['Stroll at Kanpur Zoo', 'Visit Massacre Ghat', 'Walk along Kahn Riverfront'],
  Lucknow:   ['Explore Bara Imambara', 'Tour Lucknow Museum', 'Admire Rumi Darwaza'],
  Nagpur:    ['Pray at Ramtek Temple', 'Picnic at Ambazari Lake', 'Visit Sitabuldi Fort'],
  Patna:     ['Visit Patna Museum', 'Climb Golghar', 'Pray at Takht Sri Harmandir Sahib'],
  Indore:    ['Shop at Sarafa Bazaar', 'Tour Raja Ramana Palace', 'See Jhansi Ki Rani Statue'],
  Vadodara:  ['Explore Lakshmi Vilas Palace', 'Walk in Sayaji Garden', 'Visit Meer Khan Palace'],
  Bhopal:    ['Hike in Bhimbetka Caves', 'Boat on Upper Lake', 'Visit Tribal Museum'],
  Ludhiana:  ['Explore Pau Papne Wali Baoli', 'Visit Planetarium', 'Tour Atal Bihari Vajpayee Memorial'],
  Udaipur:   ['Tour City Palace', 'Boat ride on Lake Pichola', 'Visit Jag Mandir'],
  Shimla:    ['Stroll on The Ridge', 'Shop at Mall Road', 'Visit Jakhoo Temple'],
  Darjeeling:['Watch sunrise at Tiger Hill', 'Ride the Toy Train', 'Visit Zoological Park'],
  Kochi:     ['Explore Fort Kochi', 'See Chinese Fishing Nets', 'Visit Mattancherry Palace'],
  Mysore:    ['Marvel at Mysore Palace', 'Visit Chamundeshwari Temple', 'Walk in Brindavan Gardens'],
  Chandigarh: ["Boating at Sukhna Lake","Stroll in Rock Garden","Shop in Sector 17"],
  Guwahati: ["River cruise on Brahmaputra","Visit Kamakhya","Explore Umananda"],
  Bhubaneswar: ["Temple tour","Explore ancient caves","Visit the Zoo"],
  Trivandrum: ["Pray at Temple","Visit Museum","Relax at Kovalam"],
  Madurai: ["Temple visit","Palace tour","Street food"],
  Jodhpur: ["Fort tour","Zip lining","Palace visit"],
  Pondicherry: ["Beach walk","Visit Auroville","French quarter tour"],
  Leh: ["Lake camping","Monastery tour","Mountain biking"],
  Manali: ["Snow sports","Trekking","Temple visit"],
  Rishikesh: ["River rafting","Yoga retreat","Ganga Aarti"],
}
